# This is a basic workflow to help you get started with Actions

name: Django CD

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port:  ${{ secrets.PORT }}
        script: |
          cd ~/olduglyhomes.com
          git pull origin main
          git status
          source ~/olduglyhomes.com/venv/bin/activate
          python manage.py collectstatic --no-input
          sudo systemctl restart gunicorn_olduglyhomes
          sudo supervisorctl restart celery_olduglyhomes
          sudo supervisorctl restart celery_beat_olduglyhomes
          sudo systemctl reload nginx